version: '3'
services:
  nodered:
    image: nodered/node-red
    container_name: privateCA
    restart: always
    user: '0'    
    volumes:
      - ./nodered:/data
    ports:
      - '8443:1880'
