version: '3'
services:
  nodered:
    image: nodered/node-red
#    build: 
#      context: .
#      dockerfile: Dockerfile
    container_name: privateCA
    restart: always
    user: '0'    
#    command: supervisord -n
    volumes:
      - ./nodered:/data
    ports:
      - '8443:1880'
      - '9999:9999'

